apiVersion: v1
kind: Service
metadata:
  name: cloud-native-go-facade
  namespace: cloud-native-go
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: cloud-native-go-facade

